### PR TITLE
Shrinking Jenkins Font Size to support triple digit numbers :-(

### PR DESCRIPTION
**Pull request by pcorliss**

### CODE REVIEW

**Comment by b1naryth1ef** [comment]
:+1:

**Comment by ssgelm** [comment]
Could this be used to dynamically fit it? http://dev.w3.org/csswg/css-values/#viewport-relative-lengths

**Comment by ssgelm** [comment]
I got this working dynamically with #46.

**Comment by mikepilat** [comment]
Superceded by #46

**Pull request closed without merging**
